name: arbaz_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^6.3.3
  http: ^1.6.0
  intl: ^0.20.2
  provider: ^6.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  sign_in_button: ^4.0.1
  tap_debouncer: ^2.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  change_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
      - images/
